### ISSUE TITLE
Looking into update action, but so is ansible-galaxy

### ISSUE THREAD

**Issue by RealLukeMartin** [short-stack/short-stack#2]
Might need to be future feature, or keep looking into workaround solution.

https://github.com/ansible/ansible/issues/6466

**Comment by RealLukeMartin** [comment]
Future feature

https://github.com/short-stack/short-stack/commit/584c64108e38d6fa4b9b94f7d1948bebfae11a0a

**Comment by ssbarnea** [comment]
Why is this issue closed? It is clearly not fixed and very important.

**Comment by RealLukeMartin** [comment]
We are waiting on Ansible Galaxy to fix this issue ansible/ansible#6466. Will reopen when notified they have a solution.
